function PData = TDE_PData(P, Trans)
% Define PData object.

% Define pixel resolution in wavelengths
x_res = Trans.spacing;
z_res = 0.5;

PData(1) = struct( ...
    'PDelta', ... % voxel resolution (X, Y ,Z)
            [x_res, 0, z_res], ... 
    'Size', ...   % imageBuffer dimensions (Z, X, Frames)
            [ceil((P.endDepth - P.startDepth) / z_res), ... 
            ceil(Trans.numelements * Trans.spacing / 3 / x_res), ...
            1], ...
    'Origin', ... % upper left corner (X, Y, Z)
            [-Trans.spacing * (Trans.numelements - 1) / 6, ...
            0, ...
            P.startDepth]);

end
