function DisplayWindow = TDE_DisplayWindow(PData)
% Specify Display Windows

% Common parameters
pdelta = 0.35; % new pixel resolution for interpolation [wavelengths]
WinWidth = ceil(PData(1).Size(2) * PData(1).PDelta(1) / pdelta);
WinHeigth = ceil(PData(1).Size(1) * PData(1).PDelta(3) / pdelta);

% #1: B-mode image window
DisplayWindow(1) = struct( ...
    'Title', 'B-mode image', ...
    'pdelta', pdelta, ...
    'ReferencePt', PData.Origin, ...
    'Type', 'Verasonics', ...
    'numFrames', 1, ...
    'AxesUnits', 'mm', ...
    'Colormap', gray(256), ...
    'Position', ...  % lower left corner position x, y, width % heigth
                [0, 0, ...
                WinWidth, WinHeigth]);

end
